#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_before = "myconfig#before"
    bootstrap_after = "myconfig#after"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  autocomplete_method = "coc"
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'default'

[[layers]]
  name = 'shell'
  default_position = 'bootom'
  default_height = 15

[[layers]]
  name = "git"

[[layers]]
  name = "debug"

[[layers]]
  name = 'fzf'

[[layers]]
  name = 'lang#xml'

[[layers]]
  name = "lang#python"
  format_on_save = 1
  enabled_linters = ['pylint']

[[layers]]
  name = "lang#plantuml"
  enable_typeinfo = true

[[layers]]
  name = "lang#php"

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
  clang_executable = "/usr/bin/clang"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#scala"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "gtags"
  gtagslabel = "pygments"

[[layers]]
  name = "lang#java"

[[layers]]
  name = "lsp"
  filetypes = [
    "java",
    "cpp",
    "c"
  ]
  [layers.override_cmd]
    java = [
    "java",
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=NONE",
    "-noverify",
    "-Xmx2G",
    "-Xms1G",
    "-jar",
    "$HOME/jls/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar",
    "-configuration",
    "$HOME/jls/config_win",
    "-data",
    "$HOME/.cache/javalsp"
    ]

[[layers]]
  name = "checkers"
  show_cursor_error = false

[[custom_plugins]]
name = 'neovim/nvim-lspconfig'
merged = 0
[[custom_plugins]]
name = 'szw/vim-maximizer'
merged = 0
[[custom_plugins]]
name = 'puremourning/vimspector'
merged = 0
[[custom_plugins]]
name = 'Shougo/vimproc.vim'
merged = 0
[[custom_plugins]]
name = 'hashivim/vim-terraform'
merged = 0
[[custom_plugins]]
name = 'nvim-lua/popup.nvim'
merged = 0
[[custom_plugins]]
name = 'nvim-lua/plenary.nvim'
merged = 0
[[custom_plugins]]
name = 'nvim-telescope/telescope.nvim'
merged = 0
[[custom_plugins]]
name = 'nvim-treesitter/playground'
merged = 0
[[custom_plugins]]
name = 'nvim-treesitter/nvim-treesitter'
merged = 0
[[custom_plugins]]
name = 'kyazdani42/nvim-web-devicons'
merged = 0
[[custom_plugins]]
name = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
