#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================
# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "tokyonight"
   # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_before = "myconfig#before"
    bootstrap_after = "myconfig#after"

[[layers]]
name = "core"
enable = false 
[[layers]]
 name = 'autocomplete'
 autocomplete_method = "coc"
 auto_completion_return_key_behavior = "complete"
 auto_completion_tab_key_behavior = "smart"
[[layers]]
  name = 'default'
[[layers]]
  name = "git"
[[layers]]
  name = "debug"
[[layers]]
  name = 'fzf'
[[layers]]
  name = 'lang#xml'
[[layers]]
  name = "lang#plantuml"
  enable_typeinfo = true
[[layers]]
  name = "lang#php"
[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
  clang_executable = "/usr/bin/clang"
[[layers]]
  name = "lang#dockerfile"
[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true
[[layers]]
  name = "lang#html"
[[layers]]
  name = "lang#scala"
[[layers]]
  name = "lang#sh"
[[layers]]
  name = "lang#vim"
[[layers]]
  name = "gtags"
  gtagslabel = "pygments"
[[layers]]
  name = "lang#java"
[[layers]]
  name = "checkers"
  show_cursor_error = false
[[layers]]
  name = "sudo"
[[layers]]
  name = "tools"
[[layers]]
  name = "edit"
[[layers]]
  name = "treesitter"
[[custom_plugins]]
  name = 'wbthomason/packer.nvim'
  merged = 0
