- name: "localhost"
  hosts: localhost 
  become_method: sudo
  become_user: root
  become: no
  vars:
    ansible_python_interpreter: python3
    ansible_pkg_mgr: apt
    eclipse_base_dir: "${HOME}/IDE/eclipse" 
  environment:    
    NIXPKGS_ALLOW_UNFREE: 1
    PATH: "/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:/usr/bin:/bin"
  tasks:  
    - name: Include task list
      include_tasks: "ansible/tasks/main.yml"


