IMAGE_NAME = "bento/ubuntu-24.04"

Vagrant.configure("2") do |config|

    config.vm.box = IMAGE_NAME

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
        v.gui = true
    end

    config.vm.provider "vmware_desktop" do |v|
        v.memory = 4096
        v.cpus = 4
        v.gui = true
    end

    config.vm.define "master" do |master|
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "vm-deploy.yml"
            ansible.verbose = "vv"
            ansible.extra_vars = {
                node_ip: "192.168.50.10",
            }
        end
    end
end
