 
---
- include: apt.yml
- include: zsh.yml
- include: gh-cli.yml
- include: docker.yml
- include: jenv.yml
- include: snap.yml
- include: kubernetes.yml
- include: fasd.yml
- include: spacevim.yml
- include: npm.yml
- include: brew.yml
- include: serverless.yml
- include: terraform.yml  
- include: pip.yml
- include: sdkman.yml
- include: java-language-server.yml
- include: nvim.yml
- include: aws.yml

    
- name: Install nnn plugins 
  get_url:
      url: https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs
      dest: /tmp/plugins.sh
      mode: +x
  become: false

- name: Execute the plugins.sh
  shell: /tmp/plugins.sh

- name: Remove the plugins.sh
  file: path=/tmp/plugins.sh state=absent
    
  
