
    
- name: Download nvim app image 
  get_url:
      url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
      dest: /home/linuxbrew/.linuxbrew/bin/nvim.appimage
      mode: +x
  become: false
  ignore_errors: yes

- name: Permision for nvim app image
  shell: chmod u+x /home/linuxbrew/.linuxbrew/bin/nvim.appimage 
  ignore_errors: yes
  become: false

- name: nvim symlink
  file: 
    path: /home/linuxbrew/.linuxbrew/bin/nvim 
    mode: u+x
    src: /home/linuxbrew/.linuxbrew/bin/nvim.appimage
    state: link 
    force: no
  become: false
  ignore_errors: yes


- name: tree-sitter
  get_url:
    url: https://github.com/tree-sitter/tree-sitter/releases/download/v0.20.0/tree-sitter-linux-x64.gz
    dest: $HOME/.local/bin/tree-sitter.gz
  become: false
  ignore_errors: yes

- name: extract tree.sitter
  unarchive:
    src: $HOME/.local/bin/tree-sitter.gz
    dest: $HOME/.local/bin/tree-sitter
  ignore_errors: yes

