- name: Install pip3
  shell: curl https://bootstrap.pypa.io/get-pip.py -o $HOME/get-pip.py && python3 $HOME/get-pip.py
  args:
    executable: /bin/zsh
    warn: no
  become: true
  
- name: Install "flake8" package globally.
  pip:
    name: flake8
  become: true

- name: Install "yapf" package globally.
  pip:
    name: yapf
  become: true

- name: Install "autoflake" package globally.
  pip:
    name: autoflake
  become: true

- name: Install "isort" package globally.
  pip:
    name: isort
  become: true

- name: Install "coverage" package globally.
  pip:
    name: coverage
  become: true

- name: Install "python-language-server" package globally.
  pip:
    name: python-language-server
  become: true


- name: Install "pynvim" package globally.
  pip:
    name: pynvim
  become: true

- name: Install "pygments" package globally.
  pip:
    name: pygments
  become: true

- name: Install "trollius" package globally.
  pip:
    name: trollius
  become: true

- name: Install "greenlet" package globally.
  pip:
    name: greenlet 
  become: true

- name: Install "mycli" package globally.
  pip:
    name: mycli 
  become: true
  
- name: Install "pgcli" package globally.
  pip:
    name: pgcli 
  become: true

- name: Install "sqllite-cli" package globally.
  pip:
    name:  litecli
  become: true
