- name: Install microk8s
  snap:
    name:
      - microk8s
    classic: yes
    channel: latest/stable
  ignore_errors: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  become: true

- name: Install dbeaver
  snap:
    name:
      - dbeaver-ce
    classic: yes
    channel: latest/edge
  ignore_errors: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  become: true

- name: Install vs code
  snap:
    name:
      - code
    classic: yes
  ignore_errors: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  become: true

- name: Install eclipse
  snap:
    name:
      - eclipse
    classic: yes
  ignore_errors: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  become: true

- name: Install ccls
  snap:
    name:
      - ccls
    classic: yes
  ignore_errors: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  become: true

