- name: Ensure apt keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/trusted.gpg.d
    state: directory
    mode: "0755"
  become: true
  when: ansible_facts.distribution == "Ubuntu"

- name: Add Helix PPA signing key
  ansible.builtin.apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x355A4FA515D7C855
    keyring: /etc/apt/trusted.gpg.d/helix-editor.gpg
    state: present
  become: true
  when: ansible_facts.distribution == "Ubuntu"

- name: Add Helix PPA and update apt cache
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/helix-editor.gpg] https://ppa.launchpadcontent.net/maveonair/helix-editor/ubuntu {{ ansible_distribution_release }} main"
    filename: helix-editor
    state: present
    update_cache: yes
  become: true
  ignore_errors: true
  when: ansible_facts.distribution == "Ubuntu"

- name: Install Helix
  ansible.builtin.apt:
    name: helix
    state: present
    update_cache: yes
  become: true
  ignore_errors: true
  when: ansible_facts.distribution == "Ubuntu"
