- name: Download Kiro .deb package
  ansible.builtin.get_url:
    url: "https://prod.download.desktop.kiro.dev/releases/stable/linux-x64/signed/{{kiro_metadata.json.currentRelease}}/deb/kiro-ide-{{kiro_metadata.json.currentRelease}}-stable-linux-x64.deb"
    dest: /tmp/kiro-latest.deb
    mode: '0644'
  become: false

- name: Install Kiro
  ansible.builtin.apt:
    deb: /tmp/kiro-latest.deb
    state: present
  become: true

- name: Clean up Kiro .deb package
  ansible.builtin.file:
    path: /tmp/kiro-latest.deb
    state: absent
