 
---
- name: Install packages with apt 
  apt:
    state: present
    update_cache: yes
    pkg:
      - zsh
      - mc
      - zoxide
      - fzf
  ignore_errors: yes 
  become: true

- name: Include shared zsh setup
  include_tasks: zsh-core.yml

- name: change shell to zsh for current user
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true
