- name: Check if oh-my-zsh already installed
  stat:
    path: ~/.oh-my-zsh
  register: previous_zsh_installation
  become: false

- name: Cloning  oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    depth: 1
  register: cloning
  when: not previous_zsh_installation.stat.exists
  become: false

- name: zsh-history-substring-search
  git:
    repo: https://github.com/zsh-users/zsh-history-substring-search.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-history-substring-search
    depth: 1
  become: false

- name: zsh-vi-mode
  git:
    repo: https://github.com/jeffreytse/zsh-vi-mode.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-vi-mode
    depth: 1
  become: false

- name: zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1
  become: false

- name: zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1
  become: false

- name: Clone or update dotfiles
  git:
    repo: https://github.com/JoTerrance/.DotFiles.git
    dest: ~/.DotFiles
    depth: 1
    update: yes
    force: yes
  become: false

- name: zshrc symlink
  file:
    src: ~/.DotFiles/.zshrc
    dest: ~/.zshrc
    state: link
    force: yes

- name: Installing zsh completions
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
    depth: 1
  become: false

- name: Installing-pure-prompt
  git:
    repo: https://github.com/sindresorhus/pure.git
    dest: ~/.zsh/pure
    version: main
    depth: 1
  become: false
