- name: Install packages with apt 
  apt:
    state: present
    update_cache: yes
    pkg:
      - python3
      - python3.10-venv
      - libpq-dev
      - php-cli
      - snapd
      - build-essential
      - mc
      - net-tools
      - terminator
      - curl
      - wget
      - git
      - git-gui
      - zsh
      - unzip
      - fonts-powerline
      - maven
      - npm
      - global
      - exuberant-ctags
      - bat 
      - fd-find
      - nnn 
      - chromium-browser
      - clang
      - clangd
      - atool
      - libx11-dev 
      - libxext-dev 
      - libxft-dev
      - stterm
      - gh
  ignore_errors: yes 
  become: true

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  become: true
