- name: Install packages with apt 
  apt:
    state: present
    update_cache: yes
    pkg:
      - python3
      - python3-pip 
      - python3-wheel
      - libpq-dev
      - openjdk-17-jdk
      - openjdk-21-jdk
      - build-essential
      - mc
      - net-tools
      - terminator
      - tmuxinator
      - ripgrep
      - curl
      - wget
      - git
      - git-gui
      - zsh
      - unzip
      - fonts-powerline
      - maven
      - gradle
      - npm
      - global
      - exuberant-ctags
      - bat 
      - fd-find
      - nnn 
      - chromium-browser
      - clang
      - clangd
      - cmake
      - cargo
      - atool
      - libx11-dev 
      - libxext-dev 
      - libxft-dev
      - stterm
      - podman
      - gh
      - zoxide
      - tree
  ignore_errors: yes 
  become: true

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  become: true
