- name: Download Homebrew install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install.sh
    dest: /tmp/install_homebrew.sh
    mode: '0755'
  become: false

- name: Run Homebrew installer
  shell: /bin/bash /tmp/install_homebrew.sh
  args:
    creates: /opt/homebrew/bin/brew   # Cambia a /usr/local/bin/brew en Intel Mac
    executable: /bin/bash
  become: false

- name: Export brew into path
  blockinfile:
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK for linuxbrew"
    block: |
      export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"

- name: Reload zshrc
  shell: . ${HOME}/.zshrc
  args:
    executable: /bin/zsh
  ignore_errors: yes
  become: false

- name: Update brew
  shell: brew update
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:/usr/bin:/bin"
  ignore_errors: yes
  become: false
  

- name: Homebrew upgrading all
  homebrew:
    upgrade_all: yes
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:/usr/bin:/bin"
  ignore_errors: yes


- name: Install lazygit lazydocker lazynpm dry using Brew Tap
  community.general.homebrew_tap:
    name: jesseduffield/lazydocker,hashicorp/tap,jesseduffield/lazygit,jesseduffield/lazynpm,moncho/dry
    state: present
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:/usr/bin:/bin"

- name: Install packages with Homebrew
  homebrew:
    name: "{{ item }}"
    path: /home/linuxbrew/.linuxbrew/bin
    state: latest
  loop:
    - tig
    - ctop
    - helm
    - lf
    - dive
    - stern
    - tmuxinator
    - ripgrep
    - lnav
    - terraform
    - dry
    - lazygit
    - lazydocker
    - lazynpm
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:/usr/bin:/bin"
  ignore_errors: yes
  become: false

- name: Downloading fzf github
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    depth: 1

- name: Installing fzf
  shell: "~/.fzf/install"

- name: Ensure zsh completions directory exists
  ansible.builtin.file:
    path: /usr/local/share/zsh/site-functions
    state: directory
    mode: '0755'
  vars:
    ansible_command_timeout: 30
  become: true
  ignore_errors: yes

- name: Generate GitHub CLI zsh completion file
  ansible.builtin.command:
    cmd: gh completion -s zsh
  register: gh_completion
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:/usr/bin:/bin"
  changed_when: false
  ignore_errors: yes

- name: Write gh completion script to zsh site-functions
  ansible.builtin.copy:
    content: "{{ gh_completion.stdout }}"
    dest: /usr/local/share/zsh/site-functions/_gh
    mode: '0644'
  become: true
  when: gh_completion.rc == 0
