- name: Add an apt signing key for Docker
  shell:
    cmd:  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg
  become: true

- name: Add apt repository for stable version
  shell:
    cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: true

- name: Install docker and its dependecies
  apt:
    state: present
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  ignore_errors: yes
  become: true
