 
---
- include_tasks: nix.yml
- include_tasks: apt.yml
- include_tasks: zsh.yml
- include_tasks: docker.yml
- include_tasks: jenv.yml
- include_tasks: npm.yml
- include_tasks: brew.yml
- include_tasks: pip.yml
- include_tasks: sdkman.yml 
- include_tasks: nvim.yml
- include_tasks: nnn.yml
- include_tasks: grv.yml
- include_tasks: code.yml
- include_tasks: zed.yml
- include_tasks: helix.yml
  
