- name: Install nnn plugins 
  get_url:
      url: https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs
      dest: /tmp/plugins.sh
      mode: +x
  become: false

- name: Execute the plugins.sh
  shell: /tmp/plugins.sh

- name: Remove the plugins.sh
  file: path=/tmp/plugins.sh state=absent