- name: Download nvm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
    dest: /tmp/install_nvm.sh
    mode: '0755'
  become: false

- name: Run nvm installer
  ansible.builtin.command:
    cmd: zsh /tmp/install_nvm.sh
  args:
    chdir: /tmp
  become: false
  environment:
    PROFILE: "~/.zshrc"
  creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install node in zsh
  shell: source ~/.zshrc && nvm install node
  args:
    executable: /bin/zsh
  become: false
  ignore_errors: true
   
- name: Install npm in zsh
  shell: source ~/.zshrc && nvm install-latest-npm
  args:
   executable: /bin/zsh
  become: false  
  ignore_errors: true

- name: Install nvm in bash
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

- name: Install "pyright" package globally.
  npm:
    name: pyright
    global: yes
  become: true

- name: Install "dockly" package globally.
  npm:
    name: dockly
    global: yes
  become: true

- name: Install "fkill-cli" package globally.
  npm:
    name: fkill-cli
    global: yes
  become: true
    
