- name: donwload and extract tree sitter
  unarchive:
    src: https://github.com/tree-sitter/tree-sitter/releases/download/v0.25.8/tree-sitter-linux-x64.gz
    dest: /usr/local/bin/
    remote_src: yes
  ignore_errors: yes
  become: true

- name: installing blindNvim configuration
  git:
    repo: https://github.com/JoTerrance/BlindNvim.git
    dest: ~/.config/nvim
  ignore_errors: yes


