- name: Download tree-sitter binary (gzipped)
  ansible.builtin.get_url:
    url: https://github.com/tree-sitter/tree-sitter/releases/download/v0.25.10/tree-sitter-linux-x64.gz
    dest: /usr/local/bin/tree-sitter.gz
    mode: '0644'
  become: true

- name: Decompress tree-sitter binary
  ansible.builtin.command:
    cmd: gunzip -f /usr/local/bin/tree-sitter.gz
  become: true

- name: Ensure tree-sitter is executable
  ansible.builtin.file:
    path: /usr/local/bin/tree-sitter
    mode: '0755'
    state: file
  become: true

- name: installing blindNvim configuration
  git:
    repo: https://github.com/JoTerrance/BlindNvim.git
    dest: ~/.config/nvim
    depth: 1
  ignore_errors: yes


