# Lista de paquetes a instalar con pipx
- name: Install global python tools with pipx
  ansible.builtin.command:
    cmd: "pipx install {{ item }}"
  loop:
    - flake8
    - yapf
    - thefuck
    - autoflake
    - isort
    - coverage
    - python-language-server
    - pylint
    - pynvim
    - pygments
    - mycli
    - pgcli
    - mssql-cli
    - litecli
    - iredis
  ignore_errors: true
