- name: Check if oh-my-zsh previous installed
  stat: 
    path: ~/.oh-my-zsh
  register: previous_zsh_instalation
  become: false

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    depth: 1
  register: cloning
  when: not previous_zsh_instalation.stat.exists
  become: false

- name: zsh-history-substring-search
  git:
    repo: https://github.com/zsh-users/zsh-history-substring-search.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-history-substring-search
    depth: 1

- name: zsh-vi-mode
  git:
    repo: https://github.com/jeffreytse/zsh-vi-mode.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-vi-mode
    depth: 1

- name: zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1

- name: zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1

- name: Installing git configfiles
  git:
    repo: https://github.com/JoTerrance/.DotFiles.git
    dest: ~/.DotFiles
    depth: 1
  ignore_errors: yes

- name: zshrc symlink
  file: 
    src: ~/.DotFiles/.zshrc
    dest: ~/.zshrc  
    state: link 
    force: yes

- name: mycli config folder
  file: 
    path: ~/.config/mycli/  
    state: directory 
    mode: '0755'
  ignore_errors: yes

- name: pgcli config folder
  file: 
    path: ~/.config/pgcli/  
    state: directory 
    mode: '0755'
  ignore_errors: yes

- name: litecli config folder
  file: 
    path: ~/.config/litecli/  
    state: directory 
    mode: '0755'
  ignore_errors: yes

- name: mssql config folder
  file: 
    path: ~/.config/mssqlcli/  
    state: directory 
    mode: '0755'
  ignore_errors: yes

- name: iredis config folder
  file: 
    path: ~/.config/iredis/  
    state: directory 
    mode: '0755'
  ignore_errors: yes

- name: mycli symlink
  file: 
    src: ~/.DotFiles/mycli/config 
    dest: ~/.myclirc  
    state: link 
    force: yes

- name: pgcli symlink
  file: 
    src: ~/.DotFiles/pgcli/config
    dest: ~/.config/pgcli/config
    state: link 
    force: yes

- name: litecli symlink
  file: 
    src: ~/.DotFiles/litecli/config 
    dest:   ~/.config/litecli/config
    state: link 
    force: yes

- name: mssql symlink
  file: 
    src: ~/.DotFiles/mssqlcli/config
    dest:  ~/.config/mssqlcli/config 
    state: link 
    force: yes

- name: iredis symlink
  file: 
    src: ~/.DotFiles/iredis/.iredisrc 
    dest:  ~/.iredisrc 
    state: link 
    force: yes

- name: Installing zsh completions
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
    depth: 1

- name: Installing zsh-history-substring
  git:
    repo: https://github.com/zsh-users/zsh-history-substring-search.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-history-substring-search
    depth: 1


- name: Installing-pure-prompt
  git:
    repo: https://github.com/sindresorhus/pure.git
    dest: ~/.zsh/pure
    version: main
    depth: 1

- name: change shell to zsh
  shell: "chsh -s /usr/bin/zsh"
  become: true
